# == Equation core probes: series, parity-aware gradients, residuals ===
# Next-stage development (2026-08-09).
#
# This file deliberately does NOT invent a complete generative equation.
# It implements the auditable primitives needed before G_d is frozen:
#   1. keep s (PAL), d (carrier), r (retype), t (runtime) separate;
#   2. expose candidate series L_s / W_d / Q_d without calling them frozen;
#   3. build parity-aware gradient coordinates (odd center vs even center pair);
#   4. compare numeric candidate fields with explicit residuals.
#
# Letters are not used as numerical dimensions here. Symbolic 3x3/4x4
# samples belong to the evidence layer, not to the gradient equation.

#' @title Candidate dimension series
#' @description Computes the three candidate sequences recovered from the
#'   original project. They are returned as candidate relations, not as
#'   frozen laws:
#'   \itemize{
#'     \item \code{L_s = 2s + 1}: PAL path length;
#'     \item \code{W_d = d + 2}: candidate carrier width;
#'     \item \code{Q_d = W_d + d = 2d + 2}: old-draft step count.
#'   }
#' @param s_max non-negative integer; largest PAL storage index.
#' @param d_max positive integer; largest carrier index (d starts at 1).
#' @return A list of class \code{visualr_dimension_series} with separate
#'   PAL and carrier tables, areas, adjacent differences, and status.
#' @examples
#' dimension_series(s_max = 4L, d_max = 5L)
dimension_series <- function(s_max = 8L, d_max = 8L) {
  s_max <- as.integer(s_max)
  d_max <- as.integer(d_max)
  if (length(s_max) != 1L || is.na(s_max) || s_max < 0L) {
    stop("`s_max` must be one non-negative integer.", call. = FALSE)
  }
  if (length(d_max) != 1L || is.na(d_max) || d_max < 1L) {
    stop("`d_max` must be one positive integer.", call. = FALSE)
  }

  s <- 0:s_max
  d <- seq_len(d_max)
  pal <- data.frame(
    s = s,
    L_s = 2L * s + 1L,
    stringsAsFactors = FALSE
  )
  carrier <- data.frame(
    d = d,
    W_d = d + 2L,
    Q_d = 2L * d + 2L,
    area = as.integer((d + 2L)^2),
    delta_W = c(NA_integer_, diff(d + 2L)),
    delta_Q = c(NA_integer_, diff(2L * d + 2L)),
    stringsAsFactors = FALSE
  )
  structure(
    list(
      pal = pal,
      carrier = carrier,
      status = "candidate_not_frozen",
      notes = c(
        "L_s, W_d, Q_d are separate candidate sequences.",
        "The draft extrapolation 6+4=10 is not frozen.",
        "No unknown matrix sample is generated by this function."
      )
    ),
    class = "visualr_dimension_series"
  )
}

#' @export
print.visualr_dimension_series <- function(x, ...) {
  cat("<visualr_dimension_series> status=", x$status, "\n", sep = "")
  cat("PAL series (s, L_s):\n")
  print(x$pal, row.names = FALSE)
  cat("Carrier series (d, W_d, Q_d, area):\n")
  print(x$carrier, row.names = FALSE)
  invisible(x)
}

#' @title Build a parity-aware gradient lattice
#' @description Generates coordinate and gradient metadata without
#'   assigning symbolic values. Odd widths have one geometric center;
#'   even widths have a center set. Gradient is the Manhattan distance to
#'   the nearest center location, so the center rule is explicit rather
#'   than silently assuming one singularity.
#' @param width positive integer matrix width.
#' @return A data frame with row/col, gradient, center flag, parity and
#'   center-set metadata, classed as \code{visualr_gradient_lattice}.
#' @examples
#' gradient_lattice(3L)
#' gradient_lattice(4L)
gradient_lattice <- function(width) {
  width <- as.integer(width)
  if (length(width) != 1L || is.na(width) || width < 1L) {
    stop("`width` must be one positive integer.", call. = FALSE)
  }
  if (width %% 2L == 1L) {
    mid <- (width + 1L) / 2L
    centers <- matrix(c(mid, mid), ncol = 2L,
                      dimnames = list(NULL, c("row", "col")))
    center_mode <- "odd_single_center"
  } else {
    lo <- width / 2L
    hi <- lo + 1L
    centers <- rbind(c(lo, lo), c(lo, hi), c(hi, lo), c(hi, hi))
    colnames(centers) <- c("row", "col")
    center_mode <- "even_center_set"
  }

  coords <- expand.grid(row = seq_len(width), col = seq_len(width))
  coords$gradient <- as.integer(apply(coords[c("row", "col")], 1L, function(x) {
    min(abs(centers[, "row"] - x[["row"]]) +
          abs(centers[, "col"] - x[["col"]]))
  }))
  coords$is_center <- coords$gradient == 0L
  coords$width <- width
  coords$parity <- if (width %% 2L == 0L) "even" else "odd"
  coords$center_mode <- center_mode
  attr(coords, "centers") <- centers
  class(coords) <- c("visualr_gradient_lattice", class(coords))
  coords
}

#' @title Extract gradient metadata
#' @description Returns the center coordinates and gradient summary for a
#'   lattice. This is an observation object, not a claim about symbolic
#'   values in an unknown matrix.
#' @param lattice a \code{visualr_gradient_lattice}.
#' @return list with centers, center_mode, max_gradient and width.
gradient_metadata <- function(lattice) {
  if (!inherits(lattice, "visualr_gradient_lattice")) {
    stop("`lattice` must be a visualr_gradient_lattice.", call. = FALSE)
  }
  list(
    centers = attr(lattice, "centers"),
    center_mode = unique(lattice$center_mode),
    max_gradient = max(lattice$gradient),
    width = unique(lattice$width),
    center_count = sum(lattice$is_center)
  )
}

#' @title Compute numeric gradient residuals
#' @description Compares two numeric fields element-wise. It reports
#'   residuals without declaring a target equation; this is the error
#'   instrument to use after a candidate \code{G_d} produces a field.
#' @param observed numeric matrix/vector observed or source field.
#' @param predicted numeric matrix/vector candidate-generated field.
#' @param weights optional numeric vector/matrix of non-negative weights.
#' @return list with residual field, max absolute, mean absolute, L1,
#'   L2, weighted flag and dimensions.
#' @examples
#' gradient_residual(matrix(c(0, 1, 1, 0), 2, 2),
#'                   matrix(c(0, 1, 2, 0), 2, 2))
gradient_residual <- function(observed, predicted, weights = NULL) {
  if (!is.numeric(observed) || !is.numeric(predicted) ||
      !identical(dim(observed), dim(predicted))) {
    stop("`observed` and `predicted` must be numeric with identical dimensions.",
         call. = FALSE)
  }
  if (anyNA(observed) || anyNA(predicted)) {
    stop("`observed` and `predicted` must not contain NA.", call. = FALSE)
  }
  if (is.null(weights)) {
    weights <- rep(1, length(observed))
    weighted <- FALSE
  } else {
    if (!is.numeric(weights) || !identical(dim(weights), dim(observed)) ||
        anyNA(weights) || any(weights < 0)) {
      stop("`weights` must be non-negative numeric with observed dimensions.",
           call. = FALSE)
    }
    weighted <- TRUE
  }
  residual <- observed - predicted
  abs_residual <- abs(residual)
  list(
    residual = residual,
    max_abs = max(abs_residual),
    mean_abs = mean(abs_residual),
    l1 = sum(abs_residual),
    l2 = sqrt(sum(residual^2)),
    weighted_l1 = sum(weights * abs_residual),
    weighted = weighted,
    dim = dim(observed)
  )
}

#' @title Audit a dimension sample shape
#' @description Records structural facts about a supplied matrix sample:
#'   width, parity, center count and gradient lattice. It does not infer
#'   symbolic values or invent a missing sample.
#' @param sample numeric or character square matrix.
#' @return list containing the sample, shape facts and gradient lattice.
audit_dimension_sample <- function(sample) {
  if (!is.matrix(sample) || nrow(sample) != ncol(sample) ||
      nrow(sample) < 1L) {
    stop("`sample` must be a non-empty square matrix.", call. = FALSE)
  }
  lattice <- gradient_lattice(nrow(sample))
  meta <- gradient_metadata(lattice)
  list(
    sample = sample,
    width = nrow(sample),
    parity = if (nrow(sample) %% 2L == 0L) "even" else "odd",
    center_mode = meta$center_mode,
    center_count = meta$center_count,
    gradient = lattice,
    values_uninterpreted = TRUE
  )
}
