# == Sample topology analysis: symmetries, orbits, centers ==========
# 3x3 / 4x4 PAL samples are registered as EVIDENCE (user-frozen),
# not as generated values. Analysis pipeline (external review 2026-08-09):
#   symmetry detection -> orbit partition -> geometric vs semantic
#   center separation -> label reuse detection.
#
# Key facts the analysis must reproduce:
#   - 3x3: central inversion only (M_ij = M_(4-i,4-j)); 5 orbits, no
#     label reuse; semantic center e = geometric center (single).
#   - 4x4: transpose AND central inversion (M = M^T, M = J M J);
#     6 orbits over 16 addresses; label C is REUSED across two orbits
#     (second outer rail + central main diagonal); semantic center e is
#     a PAIR on the central anti-diagonal, while the geometric center
#     set is the central 2x2 block. Content value cannot replace address.

#' @title Detect symmetry relations of a square symbol matrix
#' @description Checks transpose symmetry and central inversion
#'   (anti-diagonal flip) on a square matrix. These are structural
#'   facts about the address map, not about symbol values.
#' @param M a non-empty square character/numeric matrix.
#' @return list with transpose_ok, inversion_ok and n.
#' @examples
#' M3 <- matrix(c("A","B","C","D","e","D","C","B","A"), 3, 3, byrow = TRUE)
#' detect_symmetries(M3)
detect_symmetries <- function(M) {
  if (!is.matrix(M) || nrow(M) != ncol(M) || nrow(M) < 1L) {
    stop("`M` must be a non-empty square matrix.", call. = FALSE)
  }
  n <- nrow(M)
  inv <- M[n:1L, n:1L, drop = FALSE]
  list(
    transpose_ok = isTRUE(all.equal(M, t(M), check.attributes = FALSE)),
    inversion_ok = isTRUE(all.equal(M, inv, check.attributes = FALSE)),
    n = n
  )
}

#' @title Partition addresses into orbits under the verified symmetry group
#' @description Each address (i,j) generates an orbit by closing under
#'   the VERIFIED symmetries: central inversion (i,j) -> (n+1-i, n+1-j)
#'   and transpose (i,j) -> (j,i). Orbits are disjoint address sets.
#' @param M a non-empty square matrix.
#' @param sym optional result of detect_symmetries (recomputed if NULL).
#' @return data frame: one row per address with orbit id and label.
#' @examples
#' M4 <- matrix(c("A","B","C","D","B","C","e","C",
#'                "C","e","C","B","D","C","B","A"), 4, 4, byrow = TRUE)
#' orbit_partition(M4)
orbit_partition <- function(M, sym = NULL) {
  if (!is.matrix(M) || nrow(M) != ncol(M) || nrow(M) < 1L) {
    stop("`M` must be a non-empty square matrix.", call. = FALSE)
  }
  if (is.null(sym)) sym <- detect_symmetries(M)
  n <- nrow(M)
  trans <- sym$transpose_ok
  inv <- sym$inversion_ok

  # closure under the group generated by verified symmetries
  closure <- function(i, j) {
    acc <- list(c(i, j))
    seen <- paste(i, j, sep = ",")
    repeat {
      added <- FALSE
      cur <- acc
      for (p in cur) {
        cand <- list()
        if (inv) cand[[length(cand) + 1L]] <- c(n + 1L - p[[1L]], n + 1L - p[[2L]])
        if (trans) cand[[length(cand) + 1L]] <- c(p[[2L]], p[[1L]])
        for (q in cand) {
          k <- paste(q[[1L]], q[[2L]], sep = ",")
          if (!k %in% seen) {
            seen <- c(seen, k)
            acc[[length(acc) + 1L]] <- q
            added <- TRUE
          }
        }
      }
      if (!added) break
    }
    acc
  }

  rows <- list()
  next_orbit <- 1L
  assigned <- character()
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      key <- paste(i, j, sep = ",")
      if (key %in% assigned) next
      orb <- closure(i, j)
      for (p in orb) {
        rows[[length(rows) + 1L]] <- data.frame(
          row = p[[1L]], col = p[[2L]],
          orbit = next_orbit,
          label = M[p[[1L]], p[[2L]]],
          stringsAsFactors = FALSE
        )
      }
      assigned <- c(assigned, vapply(orb, function(p) paste(p[[1L]], p[[2L]], sep = ","), character(1L)))
      next_orbit <- next_orbit + 1L
    }
  }
  out <- do.call(rbind, rows)
  rownames(out) <- NULL
  out
}

#' @title Geometric vs semantic center separation
#' @description Geometric centers come from parity alone (odd: single
#'   center; even: central block). Semantic centers are the addresses
#'   holding the singularity token (e). The separation shows whether the
#'   two coincide — for 4x4 they do NOT: geometric set is the central
#'   2x2, semantic set is the e pair on the anti-diagonal.
#' @param M a non-empty square matrix.
#' @param singularity character; the semantic center token (default "e").
#' @return list with geometric_centers, semantic_centers, coincide.
#' @examples
#' M4 <- matrix(c("A","B","C","D","B","C","e","C",
#'                "C","e","C","B","D","C","B","A"), 4, 4, byrow = TRUE)
#' center_analysis(M4)
center_analysis <- function(M, singularity = "e") {
  if (!is.matrix(M) || nrow(M) != ncol(M) || nrow(M) < 1L) {
    stop("`M` must be a non-empty square matrix.", call. = FALSE)
  }
  n <- nrow(M)
  if (n %% 2L == 1L) {
    c0 <- (n + 1L) / 2L
    geometric <- data.frame(row = c0, col = c0, stringsAsFactors = FALSE)
  } else {
    lo <- n / 2L
    hi <- lo + 1L
    geometric <- expand.grid(row = c(lo, hi), col = c(lo, hi))
    geometric <- geometric[order(geometric$row, geometric$col), , drop = FALSE]
    rownames(geometric) <- NULL
  }
  sem <- which(M == singularity, arr.ind = TRUE)
  semantic <- data.frame(row = as.integer(sem[, "row"]),
                         col = as.integer(sem[, "col"]),
                         stringsAsFactors = FALSE)
  gk <- paste(geometric$row, geometric$col, sep = ",")
  sk <- paste(semantic$row, semantic$col, sep = ",")
  list(
    geometric_centers = geometric,
    semantic_centers = semantic,
    coincide = setequal(gk, sk),
    geometric_count = nrow(geometric),
    semantic_count = nrow(semantic)
  )
}

#' @title Detect label reuse across orbits
#' @description A label appearing in more than one orbit is REUSED: the
#'   same content value occupies different topological positions. This is
#'   the evidence that position (address) is information independent of
#'   the value.
#' @param orbits result of orbit_partition.
#' @return list with reused_labels (named by label -> orbit ids) and
#'   has_reuse.
#' @examples
#' M4 <- matrix(c("A","B","C","D","B","C","e","C",
#'                "C","e","C","B","D","C","B","A"), 4, 4, byrow = TRUE)
#' label_reuse(orbit_partition(M4))
label_reuse <- function(orbits) {
  by_label <- split(orbits$orbit, orbits$label)
  reused <- Filter(function(ids) length(unique(ids)) > 1L, by_label)
  list(
    reused_labels = lapply(reused, function(ids) sort(unique(ids))),
    has_reuse = length(reused) > 0L
  )
}

#' @title Full topology audit of a registered sample
#' @description Runs symmetry detection, orbit partition, center
#'   separation and label reuse detection on one sample matrix. The
#'   result is a structural description of the sample as evidence.
#' @param M a non-empty square matrix.
#' @param name optional character; sample name for reporting.
#' @return list with name, symmetries, orbits, centers, reuse, summary.
#' @examples
#' M3 <- matrix(c("A","B","C","D","e","D","C","B","A"), 3, 3, byrow = TRUE)
#' audit_sample_topology(M3, name = "3x3")
audit_sample_topology <- function(M, name = "sample") {
  if (!is.matrix(M) || nrow(M) != ncol(M) || nrow(M) < 1L) {
    stop("`M` must be a non-empty square matrix.", call. = FALSE)
  }
  sym <- detect_symmetries(M)
  orbits <- orbit_partition(M, sym)
  centers <- center_analysis(M)
  reuse <- label_reuse(orbits)
  n_orbits <- length(unique(orbits$orbit))
  n_labels <- length(unique(orbits$label))
  list(
    name = name,
    n = nrow(M),
    symmetries = sym,
    orbits = orbits,
    n_orbits = n_orbits,
    n_labels = n_labels,
    label_reuse_occurred = n_orbits > n_labels,
    centers = centers,
    reuse = reuse,
    summary = sprintf(
      "%s: %dx%d, %d orbits over %d labels%s",
      name, nrow(M), nrow(M), n_orbits, n_labels,
      if (reuse$has_reuse) " (label reuse)" else ""
    )
  )
}
